# Generated by Django 2.1.4 on 2018-12-26 10:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id_exercise', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('hall', models.PositiveIntegerField()),
                ('start_hour', models.PositiveIntegerField()),
                ('continue_hours', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id_type_exercise', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id_trainer', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('quota', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id_day_week', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.Trainer'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='type_exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.ExerciseType'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='week_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.WeekDay'),
        ),
    ]
