# Generated by Django 2.1.4 on 2018-12-26 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.PositiveIntegerField()),
                ('start_hour', models.PositiveIntegerField()),
                ('continue_hours', models.PositiveIntegerField()),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.Trainer')),
                ('type_exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.ExerciseType')),
                ('week_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.WeekDay')),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='continue_hours',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='start_hour',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='type_exercise',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='week_day',
        ),
        migrations.AddField(
            model_name='exercise',
            name='requestexercise_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='sport.RequestExercise'),
            preserve_default=False,
        ),
    ]
